name: Build under Ubuntu

on: push

jobs:
  build:
    name: Build under Ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: zulu
          cache: gradle

      - name: Substitute Gradle settings file
        shell: bash
        run: ./substitute-settings.sh
        env:
          MC_JAVA_VERSION: "2.0.0-SNAPSHOT.151"
          CORE_VERSION: "2.0.0-SNAPSHOT.141"
          PROTO_DATA_VERSION: "0.8.5"
          VALIDATION_VERSION: "2.0.0-SNAPSHOT.81"

      - name: Build project and run tests
        shell: bash
        run: ./gradlew build --stacktrace
