name: Build

on: push

jobs:
  build:
    name: Build

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: zulu

      - name: Substitute Gradle settings file
        shell: bash
        run: ./substitute-settings.py
        env:
          MC_JAVA_VERSION: "2.0.0-SNAPSHOT.151"
          CORE_VERSION: "2.0.0-SNAPSHOT.141"
          PROTO_DATA_VERSION: "0.8.5"
          VALIDATION_VERSION: "2.0.0-SNAPSHOT.81"

      - name: Build project
        shell: bash
        # For the reason on `--no-daemon` see https://github.com/actions/cache/issues/454
        run: ./gradlew build --stacktrace --no-daemon
